before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - sudo apt-get update
    - sudo apt-get upgrade -y
    - sudo apt-get install python-pip qemu-utils -y
    - pip install diskimage-builder 
    - pip install pyyaml

stages:
    - build

build:
    stage: build
    script:
        - ./build.py 
