before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

build-and-deploy:
  stage: build
  tags:
    - dib
    - cloud
  script:
    - dib-builder/build.py
    - dib-builder/deploy.py
