before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    
variables:
    LANG: "en_US.UTF-8"
    
stages:
    - build

build:
    stage: build
    tags:
        - dib
        - cloud
    script:
        - ./build.py
        - ls -la *.qcow2
