image: bohai/diskimage-builder-dockerfile

before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - pip install pyyaml

stages:
    - build

build:
    stage: build
    script:
        - ./build.py 
