# The name of the cloud image will be created from the name and the version.
name: bioinfo-desktop
version: 0.1.2
maintainers: [Lukas Jelonek - lukas.jelonek@computational.bio.uni-giessen.de]

# The description will be used for generated websites
description: An ubuntu image that contains an xfce desktop and x2go 
# A list of installed tools worth mentioning. 
# Will be used as documentation, e.g. on a homepage
tools: [xfce, x2go]

# A list of tags to classify images. 
tags: [desktop]

# Information needed for the execution of diskimage-builder
dib:
    # architecture of the image
    architecture: amd64
    # list of elements to include in the image
    elements: [ubuntu, vm, xfce-desktop, conda-biotools]
    # package names that should be installed, -p in dib
    packages: [linux-generic-hwe-16.04-edge]

# Information needed for image deployment
deploy:
    min_cpu: 1
    min_ram: 8192 #MB
    min_hd: 20  #GB
